title: Cuttlephone
description: 3D printable phone cases
logo: /images/website-logo.png
baseurl: 
repository: SiloCityLabs/Cuttlephone
models_url: /premade-models/
guide_url: /guides/
generator_guide_url: /generator-guide/
github: [metadata]
github:
  repository_url: https://github.com/SiloCityLabs/Cuttlephone
shop_url: https://shop.silocitylabs.com/collections/3d-prints/cuttlephone

# theme and theme configuration
# https://github.com/just-the-docs/just-the-docs
remote_theme: just-the-docs/just-the-docs
#theme: just-the-docs
#color_scheme: "dark"
search_enabled: true
aux_links_new_tab: true
nav_external_links:
  - title: Code on Github
    url: https://github.com/SiloCityLabs/Cuttlephone
  - title: Shop
    url: https://shop.silocitylabs.com/collections/3d-prints/cuttlephone
callouts:
  warning:
    title: Warning
    color: red

# need for block attributes: https://kramdown.gettalong.org/quickref.html#block-attributes
markdown: kramdown
kramdown:
  #input: GFM
  input: Kramdown
  syntax_highlighter: rouge

plugins:
- jekyll-default-layout
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
- jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
