services:
  jekyll:
    build: .
    environment:
      - JEKYLL_GITHUB_TOKEN
    ports:
      - "4000:4000"
    volumes:
    #on Windows Docker, sharing volumes requires Hyper-V not WSL2
      - ./:/usr/src/app
      # copy config for names and build flags
      - ../phone_case.json:/usr/src/app/_data/phone_case.json:ro
    tty: true
