# Ruby Gems for running the website locally

source "https://rubygems.org"

# gems intended for ruby 3.3
gem "jekyll", "~> 4.4"
# jekyll requires webrick
gem "webrick"
# gem supplies jekyll-include-cache and jekyll-seo-tag for the remote theme
# keep the version in sync with remote_theme in _config.yml
gem "just-the-docs", "0.12.0"
gem "jekyll-default-layout"

group :jekyll_plugins do
  gem "jekyll-remote-theme"
  gem "jekyll-mentions"
  gem "jekyll-redirect-from"
  gem "jekyll-sitemap"
  gem "jemoji"
end

# Windows and JRuby don't include zoneinfo files, so bundle tzinfo-data
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.2", :platforms => [:mingw, :x64_mingw, :mswin]
