# Ruby Gems for running the website locally

source "https://rubygems.org"

gem "just-the-docs", "0.10.0"
gem "jekyll-default-layout"
#github-pages 222 requires:
gem "jekyll", '~> 3.9.0'
#jekyll 3.9.0 requires:
gem "webrick"

#https://github.com/pages-themes/minimal
gem "github-pages", '~> 222', group: :jekyll_plugins
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-remote-theme"
  gem "jekyll-github-metadata"
  gem "jekyll-mentions"
  gem "jekyll-redirect-from"
  gem "jekyll-sitemap"
  gem "jemoji"
  gem "kramdown-parser-gfm", "~> 1.1"
end

#https://github.com/gjtorikian/html-pipeline#dependencies
group :htmlpipeline do
  gem 'commonmarker', '~> 0.16', require: false
  #gem 'email_reply_parser', '~> 0.5', require: false
  #gem 'gemoji', '~> 2.0', require: false
  gem 'minitest'
  gem 'RedCloth','~> 4.2.9'
  gem 'rinku',              '~> 1.7',   require: false
  gem 'sanitize',           '~> 4.6', require: false

  gem 'escape_utils', '~> 1.0', require: false
  #gem 'rouge', '~> 3.1', require: false
  gem 'rouge'
  gem 'minitest-focus', '~> 1.1'
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
